channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - scikit-learn
  - jupyter
  - pandas
  - seaborn
  - requests
  - click
  - wandb
  - mlflow
  - scikit-optimize
  - pip:
    - watermark
    - pytest